
SET(OE_SWIG_INTERFACES "")
SET(OE_SWIG_DIRS "")

MACRO(DIR_NAME var file)
  SET(${var} "")
  STRING(REGEX REPLACE "^(.*/)?([^/]+)$" "\\1" ${var} ${file})
ENDMACRO(DIR_NAME)


MACRO(OE_ADD_SWIG_INTERFACES)
  FOREACH(FILE ${ARGV})
    SET (OE_SWIG_INTERFACES ${OE_SWIG_INTERFACES} "${FILE}")
    #SET (OE_SWIG_INTERFACES ${OE_SWIG_INTERFACES} "${CMAKE_CURRENT_SOURCE_DIR}/${FILE}")
    DIR_NAME(DIR ${FILE})
    SET (OE_SWIG_DIRS ${OE_SWIG_DIRS} ${DIR})
  ENDFOREACH(FILE)
ENDMACRO(OE_ADD_SWIG_INTERFACES)


SET(SWIG_FOUND true)

SET(SWIG_DIR ${OE_CURRENT_EXTENSION_DIR}/swig)

SET(SWIG_EXECUTABLE ${SWIG_DIR}/swig)
SET(SWIG_VERSION 2.0.1)


INCLUDE(${CMAKE_ROOT}/Modules/UseSWIG.cmake)
# SET(REFLECT_INCLUDE_PATH ${SWIG_DIR}/Lib/reflect)
# INCLUDE_DIRECTORIES(${REFLECT_INCLUDE_PATH})



